
- name: push "{{shinken_conf_file}}" to server
  copy:
   src: "{{shinken_conf_file}}"
   dest: "{{shinken_path_conf}}/{{shinken_conf_file}}"
   owner: "{{shinken_username}}"
   group: "{{shinken_username}}"

- name: push "{{shinken_module_webui_conf_file}}" to server
  copy:
   src: "{{shinken_module_webui_conf_file}}"
   dest: "{{shinken_path_modules}}/{{shinken_module_webui_conf_file}}"
   owner: "{{shinken_username}}"
   group: "{{shinken_username}}"

