- name: create group "{{shinken_username}}"
  group:
   name: "{{shinken_username}}"
   state: present

- name: create user "{{shinken_username}}"
  user:
   name: "{{shinken_username}}"
   group: "{{shinken_username}}"
   createhome: no
   state: present

- name: install "{{shinken_package_name}}-{{shinken_package_version}}"
  pip: 
   name: "{{shinken_package_name}}" 
   state: "{{shinken_package_version}}"
