---
- name: common plays 
  hosts: all
  roles:
   - common

# include web servers plays
#- include: webservers.yml

# include app servers plays
#- include: appservers.yml

# include db servers plays
#- include: dbservers.yml

# include monitoring servers plays
- include: monitoringsevers.yml

...
