- name: create group "{{elasticsearch_username}}"
  group:
   name: "{{elasticsearch_username}}"
   state: present

- name: create user "{{elasticsearch_username}}"
  user:
   name: "{{elasticsearch_username}}"
   group: "{{elasticsearch_username}}"
   createhome: no
   state: present

# name: set ownership of "{{elasticsearch_path_home}}" to "{{elasticsearch_username}}"
- file:
   path: "{{elasticsearch_path_home}}"
   owner: "{{elasticsearch_username}}"
   group: "{{elasticsearch_username}}"
   recurse: yes

# name: set ownership of "{{elasticsearch_path_conf}}" to "{{elasticsearch_username}}"
- file:
   path: "{{elasticsearch_path_conf}}"
   owner: "{{elasticsearch_username}}"
   group: "{{elasticsearch_username}}"
   recurse: yes

# name: set ownership of "{{elasticsearch_path_env_conf}}" to "{{elasticsearch_username}}"
- file:
   path: "{{elasticsearch_path_env_conf}}"
   owner: "{{elasticsearch_username}}"
   group: "{{elasticsearch_username}}"

# name: set ownership of "{{elasticsearch_path_data}}" to "{{elasticsearch_username}}"
- file:
   path: "{{elasticsearch_path_data}}"
   owner: "{{elasticsearch_username}}"
   group: "{{elasticsearch_username}}"
   recurse: yes

# name: set ownership of "{{elasticsearch_path_logs}}" to "{{elasticsearch_username}}"
- file:
   path: "{{elasticsearch_path_logs}}"
   owner: "{{elasticsearch_username}}"
   group: "{{elasticsearch_username}}"
   recurse: yes

- name: push "{{elasticsearch_conf_file}}" to server
  copy:
   src: "{{elasticsearch_conf_file}}"
   dest: "{{elasticsearch_path_conf}}/{{elasticsearch_conf_file}}"
   owner: "{{elasticsearch_username}}"
   group: "{{elasticsearch_username}}"

- name: push "{{elasticsearch_path_env_conf}}" to server
  copy:
   src: elasticsearch
   dest: "{{elasticsearch_path_env_conf}}"
   owner: "{{elasticsearch_username}}"
   group: "{{elasticsearch_username}}"

#
# Readonly in a docker container
# Need to change the host value, as the docker container actually run on top of
# host kernel
#
#- name: set valid value for vm.max_map_count
#  sysctl:
#   name: vm.max_map_count
#   value: 262144
#   state: present
#

# 
#- name: push /usr/lib/sysctl.d/elasticsearch.conf to server
#  copy:
#   src: elasticsearch.conf
#   dest: /usr/lib/sysctl.d/elasticsearch.conf

