- name: install elasticsearch repository
  yum_repository: 
   name: "{{elasticsearch_repository_name}}"
   description: elasticsearch "{{elasticsearch_package_version}}" repository
   baseurl: "{{elasticsearch_repository_url}}"
   gpgkey: "{{elasticsearch_repository_gpg_key}}"
   gpgcheck: yes
   enabled: yes
   state: present

- name: install "'{{elasticsearch_package_rpm}}'-'{{elasticsearch_package_version}}'"
  yum: 
   name: "{{elasticsearch_package_rpm}}" 
   state: installed

- name: check existence of x-pack plugin
  shell: "ls {{elasticsearch_path_plugins}}"
  register: installed_plugins

# @Fixme - same command run manually works fine, not this one! hmmm
- name: install x-pack
  shell: "{{elasticsearch_path_bin}}/elasticsearch-plugin install --batch x-pack"
  when: "'x-pack' not in installed_plugins.stdout"

